import Link from 'next/link'
import { notFound } from 'next/navigation'
import { AppShell } from '@/components/app-shell'
import { requireUser } from '@/lib/auth'
import { addCsiSection, addProposalItem, deleteCsiSection, deleteProposalItem, updateCommercialProposal, updateCsiSection, updateProposalItem } from '../actions'

function money(v:any){return Number(v||0).toLocaleString('en-US',{style:'currency',currency:'USD'})}
function basis(v:string){return ({lump_sum:'Lump Sum / Stipulated Sum',time_and_materials:'Time & Materials (T&M)',unit_price:'Unit Price',cost_plus:'Cost Plus Fee',gmp:'Guaranteed Maximum Price (GMP)',not_to_exceed:'Not-to-Exceed (NTE)'} as any)[v]||v}
function customerName(c:any){return c?.company_name||[c?.first_name,c?.last_name].filter(Boolean).join(' ')||'Client'}

export default async function ProposalDetail({params}:{params:Promise<{id:string}>}){
 const {id}=await params; const {supabase}=await requireUser()
 const {data:p}=await supabase.from('commercial_proposals').select('*,projects(id,project_number,project_name,project_address),customers(first_name,last_name,company_name,email,phone,billing_address),commercial_proposal_csi_sections(*),commercial_proposal_items(*)').eq('id',id).maybeSingle(); if(!p) notFound()
 const project=Array.isArray(p.projects)?p.projects[0]:p.projects; const customer=Array.isArray(p.customers)?p.customers[0]:p.customers
 const sections=[...(p.commercial_proposal_csi_sections||[])].sort((a:any,b:any)=>a.sort_order-b.sort_order); const items=[...(p.commercial_proposal_items||[])].sort((a:any,b:any)=>a.sort_order-b.sort_order)
 const base=items.filter((i:any)=>!i.is_alternate).reduce((s:number,i:any)=>s+Number(i.quantity)*Number(i.unit_price),0); const alts=items.filter((i:any)=>i.is_alternate).reduce((s:number,i:any)=>s+Number(i.quantity)*Number(i.unit_price),0)
 const update=updateCommercialProposal.bind(null,id); const addSection=addCsiSection.bind(null,id); const addItem=addProposalItem.bind(null,id)
 return <AppShell title="Commercial Proposal Builder">
  <div className="page-heading"><div><Link className="eyebrow-link" href="/commercial-proposals">← Commercial Proposals</Link><div className="project-title-line"><h2>{p.proposal_number}</h2><span className={`badge proposal-status-${p.status}`}>{p.status}</span><span className="badge">{basis(p.pricing_basis)}</span></div><p>{project?.project_number} · {project?.project_name} · {customerName(customer)}</p></div><div className="quick-actions-inline"><Link className="secondary-button" href={`/commercial-proposals/${id}/print`} target="_blank">Print / PDF</Link>{project?.id?<Link className="secondary-button" href={`/projects/${project.id}`}>Open Project</Link>:null}</div></div>
  <section className="grid-cards project-stats"><div className="card"><div className="stat-label">Base Proposal</div><div className="stat-value stat-money">{money(base)}</div></div><div className="card"><div className="stat-label">Alternates</div><div className="detail-value">{money(alts)}</div></div><div className="card"><div className="stat-label">CSI Sections</div><div className="detail-value">{sections.length}</div></div><div className="card"><div className="stat-label">Format</div><div className="detail-value">{p.template_depth}</div></div></section>

  <div className="proposal-builder-stack">
   <section className="card"><div className="section-heading"><div><h3 className="section-title">Proposal details</h3><p className="muted-copy">Use Compact for a small scope, Standard for most bids, and Detailed for large proposal packages.</p></div></div><form action={update} className="proposal-details-grid">
    <div className="field"><label>Status</label><select name="status" defaultValue={p.status}><option value="draft">Draft</option><option value="sent">Sent</option><option value="revised">Revised</option><option value="accepted">Accepted</option><option value="declined">Declined</option><option value="expired">Expired</option></select></div>
    <div className="field"><label>Trade scope</label><select name="proposal_scope_type" defaultValue={p.proposal_scope_type||'tile_and_stone'}><option value="tile_only">Tile only — 09 30 00</option><option value="stone_only">Stone countertops only — 12 36 40</option><option value="tile_and_stone">Tile + stone — separate scopes</option></select></div><label className="checkbox-row"><input type="checkbox" name="separate_trade_sheets" defaultChecked={p.separate_trade_sheets!==false}/> Start each trade scope on a separate proposal sheet when printing</label><div className="field"><label>Proposal format</label><select name="template_depth" defaultValue={p.template_depth}><option value="compact">Compact — small commercial job</option><option value="standard">Standard — typical commercial</option><option value="detailed">Detailed — large / bid package</option></select></div>
    <div className="field"><label>Pricing / contract basis</label><select name="pricing_basis" defaultValue={p.pricing_basis}><option value="lump_sum">Lump Sum / Stipulated Sum</option><option value="time_and_materials">Time & Materials (T&M)</option><option value="unit_price">Unit Price</option><option value="cost_plus">Cost Plus Fee</option><option value="gmp">Guaranteed Maximum Price (GMP)</option><option value="not_to_exceed">Not-to-Exceed (NTE)</option></select></div>
    <div className="field"><label>Proposal date</label><input type="date" name="proposal_date" defaultValue={p.proposal_date}/></div><div className="field"><label>Valid until</label><input type="date" name="valid_until" defaultValue={p.valid_until||''}/></div>
    <div className="field span-2"><label>Proposal title</label><input name="title" defaultValue={p.title}/></div><div className="field"><label>Client / GC contact</label><input name="client_contact" defaultValue={p.client_contact||''}/></div><div className="field"><label>Client / GC email</label><input name="client_email" defaultValue={p.client_email||customer?.email||''}/></div><div className="field"><label>Prepared by</label><input name="estimator" defaultValue={p.estimator||'Kevin Melendez'}/></div>
    <div className="field span-3"><label>Executive summary / proposal introduction</label><textarea name="executive_summary" rows={4} defaultValue={p.executive_summary||''} placeholder="Summarize project intent, quick-turnover capability, key scope, and proposal basis."/></div>
    <div className="field"><label>Drawings / plans reference</label><textarea name="drawings_reference" rows={3} defaultValue={p.drawings_reference||''}/></div><div className="field"><label>Specifications reference</label><textarea name="specifications_reference" rows={3} defaultValue={p.specifications_reference||''}/></div><div className="field"><label>Addenda / bid documents</label><textarea name="addenda_reference" rows={3} defaultValue={p.addenda_reference||''}/></div>
    <div className="field span-3"><label>Inclusions</label><textarea name="inclusions" rows={5} defaultValue={p.inclusions||''}/></div><div className="field span-3"><label>Exclusions</label><textarea name="exclusions" rows={5} defaultValue={p.exclusions||''}/></div><div className="field span-3"><label>Clarifications / qualifications</label><textarea name="clarifications" rows={5} defaultValue={p.clarifications||''}/></div><div className="field span-3"><label>Assumptions</label><textarea name="assumptions" rows={4} defaultValue={p.assumptions||''}/></div>
    <div className="field span-3"><label>Schedule / sequencing</label><textarea name="schedule_text" rows={4} defaultValue={p.schedule_text||''}/></div><div className="field span-3"><label>Payment / billing terms</label><textarea name="payment_terms" rows={4} defaultValue={p.payment_terms||''}/></div>
    <div className="field span-3"><label>Warranty</label><textarea name="warranty_text" rows={3} defaultValue={p.warranty_text||''}/></div><div className="field span-3"><label>Insurance / bonding</label><textarea name="insurance_bonding" rows={3} defaultValue={p.insurance_bonding||''}/></div><div className="field span-3"><label>Closeout requirements</label><textarea name="closeout_text" rows={3} defaultValue={p.closeout_text||''}/></div><div className="field span-3"><label>Alternates notes</label><textarea name="alternates_notes" rows={3} defaultValue={p.alternates_notes||''}/></div><div className="field span-3"><label>Internal / proposal notes</label><textarea name="proposal_notes" rows={3} defaultValue={p.proposal_notes||''}/></div>
    <div className="proposal-basis-box span-3"><h4>{basis(p.pricing_basis)} settings</h4><div className="proposal-rate-grid"><div className="field"><label>Standard labor rate</label><input name="labor_rate" type="number" step="0.01" defaultValue={p.labor_rate||''}/></div><div className="field"><label>Overtime labor rate</label><input name="overtime_rate" type="number" step="0.01" defaultValue={p.overtime_rate||''}/></div><div className="field"><label>Material markup %</label><input name="material_markup" type="number" step="0.01" defaultValue={p.material_markup||''}/></div><div className="field"><label>Equipment markup %</label><input name="equipment_markup" type="number" step="0.01" defaultValue={p.equipment_markup||''}/></div><div className="field"><label>Subcontractor markup %</label><input name="subcontractor_markup" type="number" step="0.01" defaultValue={p.subcontractor_markup||''}/></div><div className="field"><label>Cost Plus fee %</label><input name="cost_plus_fee" type="number" step="0.01" defaultValue={p.cost_plus_fee||''}/></div><div className="field"><label>NTE ceiling</label><input name="not_to_exceed_amount" type="number" step="0.01" defaultValue={p.not_to_exceed_amount||''}/></div><div className="field"><label>GMP amount</label><input name="gmp_amount" type="number" step="0.01" defaultValue={p.gmp_amount||''}/></div></div></div>
    <button className="primary-button span-3" type="submit">Save proposal details</button>
   </form></section>

   <section className="card"><div className="section-heading"><div><h3 className="section-title">CSI / MasterFormat scope</h3><p className="muted-copy">Organize scope by the project specification section. Use the project manual as the controlling CSI reference.</p></div><Link className="text-link" href="/settings/commercial-proposals">Manage CSI presets</Link></div>
    <div className="csi-section-list">{sections.map((s:any)=>{const save=updateCsiSection.bind(null,id,s.id);const del=deleteCsiSection.bind(null,id,s.id);return <div className="csi-section-card" key={s.id}><form action={save}><div className="csi-section-header"><div className="field"><label>CSI section</label><input name="csi_code" defaultValue={s.csi_code}/></div><div className="field csi-title-field"><label>Section title</label><input name="csi_title" defaultValue={s.csi_title}/></div><button className="secondary-button" type="submit">Save section</button></div><div className="field"><label>Scope description</label><textarea name="scope_text" rows={4} defaultValue={s.scope_text||''}/></div></form><form action={del} className="csi-delete-form"><button className="danger-button" type="submit">Remove section</button></form></div>})}</div>
    <form action={addSection} className="add-csi-section"><div className="field"><label>CSI code</label><input name="csi_code" required placeholder="09 30 00"/></div><div className="field"><label>Section title</label><input name="csi_title" required placeholder="Tiling"/></div><div className="field span-2"><label>Scope</label><textarea name="scope_text" rows={3}/></div><button className="inline-primary" type="submit">+ Add CSI section</button></form>
   </section>

   <section className="card"><div className="section-heading"><div><h3 className="section-title">Pricing schedule</h3><p className="muted-copy">Build lump-sum, unit-price, T&M, allowance, material, labor, equipment, subcontract, and alternate pricing.</p></div></div>
    <div className="proposal-item-list">{items.map((i:any)=>{const save=updateProposalItem.bind(null,id,i.id);const del=deleteProposalItem.bind(null,id,i.id);return <div className={`proposal-item-card ${i.is_alternate?'proposal-alternate':''}`} key={i.id}><form action={save} className="proposal-item-form"><div className="field proposal-item-desc"><label>Description</label><input name="description" defaultValue={i.description}/></div><div className="field"><label>CSI</label><select name="csi_section_id" defaultValue={i.csi_section_id||''}><option value="">Unassigned</option>{sections.map((s:any)=><option key={s.id} value={s.id}>{s.csi_code} · {s.csi_title}</option>)}</select></div><div className="field"><label>Type</label><select name="category" defaultValue={i.category}><option value="labor">Labor</option><option value="material">Material</option><option value="equipment">Equipment</option><option value="subcontract">Subcontract</option><option value="allowance">Allowance</option><option value="other">Other</option></select></div><div className="field"><label>Qty</label><input name="quantity" type="number" step="0.001" defaultValue={i.quantity}/></div><div className="field"><label>Unit</label><input name="unit" defaultValue={i.unit}/></div><div className="field"><label>Unit price</label><input name="unit_price" type="number" step="0.01" defaultValue={i.unit_price}/></div><label className="check-field"><input name="is_alternate" type="checkbox" defaultChecked={i.is_alternate}/> <span>Alternate</span></label><div className="field"><label>Alternate label</label><input name="alternate_label" defaultValue={i.alternate_label||''}/></div><div className="proposal-item-total"><span>Total</span><strong>{money(Number(i.quantity)*Number(i.unit_price))}</strong></div><button className="secondary-button" type="submit">Save</button></form><form action={del} className="proposal-item-delete"><button className="danger-button" type="submit">Remove</button></form></div>})}</div>
    <form action={addItem} className="proposal-item-add"><div className="field proposal-item-desc"><label>Description</label><input name="description" required placeholder="Install porcelain floor tile per plans and specifications"/></div><div className="field"><label>CSI</label><select name="csi_section_id"><option value="">Unassigned</option>{sections.map((s:any)=><option key={s.id} value={s.id}>{s.csi_code} · {s.csi_title}</option>)}</select></div><div className="field"><label>Type</label><select name="category"><option value="labor">Labor</option><option value="material">Material</option><option value="equipment">Equipment</option><option value="subcontract">Subcontract</option><option value="allowance">Allowance</option><option value="other">Other</option></select></div><div className="field"><label>Qty</label><input name="quantity" type="number" step="0.001" defaultValue="1"/></div><div className="field"><label>Unit</label><input name="unit" defaultValue="LS"/></div><div className="field"><label>Unit price</label><input name="unit_price" type="number" step="0.01" defaultValue="0"/></div><label className="check-field"><input name="is_alternate" type="checkbox"/> <span>Alternate</span></label><div className="field"><label>Alternate label</label><input name="alternate_label" placeholder="Alternate 01"/></div><button className="inline-primary" type="submit">+ Add pricing item</button></form>
   </section>
  </div>
 </AppShell>
}
