import Link from 'next/link'
import { notFound } from 'next/navigation'
import { AppShell } from '@/components/app-shell'
import { requireUser } from '@/lib/auth'
import { addPurchaseOrderItem, deletePurchaseOrderItem, updatePurchaseOrder, updatePurchaseOrderItem } from '../actions'

function money(v: number | string | null) { return Number(v || 0).toLocaleString('en-US', { style: 'currency', currency: 'USD' }) }

export default async function PurchaseOrderDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const { supabase } = await requireUser()
  const [{ data: po }, { data: vendors }] = await Promise.all([
    supabase.from('purchase_orders').select('*, vendors(id,vendor_name,contact_name,email,phone,address,payment_terms), projects(id,project_number,project_name,project_address), purchase_order_items(*)').eq('id', id).maybeSingle(),
    supabase.from('vendors').select('id,vendor_name').order('vendor_name'),
  ])
  if (!po) notFound()
  const project = Array.isArray(po.projects) ? po.projects[0] : po.projects
  const vendor = Array.isArray(po.vendors) ? po.vendors[0] : po.vendors
  const items = [...(po.purchase_order_items || [])].sort((a:any,b:any)=>a.sort_order-b.sort_order)
  const subtotal = items.reduce((s:number,i:any)=>s+Number(i.quantity||0)*Number(i.unit_cost||0),0)
  const taxable = items.filter((i:any)=>i.taxable).reduce((s:number,i:any)=>s+Number(i.quantity||0)*Number(i.unit_cost||0),0)
  const tax = taxable * (Number(po.sales_tax_rate || 0)/100)
  const total = subtotal + tax + Number(po.shipping || 0)
  const updateAction = updatePurchaseOrder.bind(null, id)
  return <AppShell title="Purchase Order">
    <div className="page-heading"><div><Link className="eyebrow-link" href="/purchase-orders">← Purchase Orders</Link><div className="project-title-line"><h2>{po.po_number}</h2><span className={`badge po-status-${po.status}`}>{po.status.replace('_',' ')}</span></div><p>{project?.project_number} · {project?.project_name} · {vendor?.vendor_name || 'No vendor selected'}</p></div><div className="quick-actions-inline"><Link className="secondary-button" href={`/projects/${po.project_id}`}>Project</Link><Link className="primary-link-button" href={`/purchase-orders/${id}/print`} target="_blank">Print / PDF</Link></div></div>
    <section className="grid-cards project-stats"><div className="card"><div className="stat-label">PO Total</div><div className="stat-value stat-money">{money(total)}</div></div><div className="card"><div className="stat-label">Subtotal</div><div className="detail-value">{money(subtotal)}</div></div><div className="card"><div className="stat-label">Tax</div><div className="detail-value">{money(tax)}</div></div><div className="card"><div className="stat-label">Freight</div><div className="detail-value">{money(po.shipping)}</div></div></section>
    <section className="po-builder-grid">
      <div className="stacked-column">
        <div className="card"><div className="section-heading"><h3 className="section-title">Line items</h3><strong>{money(total)}</strong></div>{items.length ? <div className="po-items-list">{items.map((item:any)=>{const action=updatePurchaseOrderItem.bind(null,id,item.id); const del=deletePurchaseOrderItem.bind(null,id,item.id); return <div className="po-item-editor" key={item.id}><form action={action} className="po-item-form"><div className="field po-description"><label>Description</label><input name="description" defaultValue={item.description} required /></div><div className="field"><label>Qty</label><input name="quantity" type="number" step="0.001" defaultValue={Number(item.quantity)} /></div><div className="field"><label>Unit</label><input name="unit" defaultValue={item.unit} /></div><div className="field"><label>Unit cost</label><input name="unit_cost" type="number" step="0.01" defaultValue={Number(item.unit_cost)} /></div><div className="field"><label>Received</label><input name="received_quantity" type="number" step="0.001" min="0" defaultValue={Number(item.received_quantity)} /></div><label className="checkbox-field"><input name="taxable" type="checkbox" defaultChecked={item.taxable} /> Taxable</label><button className="secondary-button">Save</button></form><form action={del}><button className="delete-button" title="Delete line item">×</button></form></div>})}</div> : <div className="empty compact-empty">Add the first material, service, or freight-related item.</div>}
          <form className="po-add-form" action={addPurchaseOrderItem.bind(null,id)}><div className="field po-description"><label>New item</label><input name="description" required placeholder="Material or service description" /></div><div className="field"><label>Qty</label><input name="quantity" type="number" step="0.001" defaultValue="1" /></div><div className="field"><label>Unit</label><input name="unit" defaultValue="EA" /></div><div className="field"><label>Unit cost</label><input name="unit_cost" type="number" step="0.01" defaultValue="0" /></div><label className="checkbox-field"><input name="taxable" type="checkbox" defaultChecked /> Taxable</label><button className="primary-button">Add item</button></form>
        </div>
        {vendor ? <div className="card"><h3 className="section-title">Vendor contact</h3><div className="contact-grid"><div><span>Vendor</span><strong>{vendor.vendor_name}</strong></div><div><span>Contact</span><strong>{vendor.contact_name || '—'}</strong></div><div><span>Email</span><strong>{vendor.email || '—'}</strong></div><div><span>Phone</span><strong>{vendor.phone || '—'}</strong></div><div className="wide"><span>Address</span><strong>{vendor.address || '—'}</strong></div></div></div> : null}
      </div>
      <form className="card po-details-card" action={updateAction}><h3 className="section-title">PO details</h3><div className="field"><label>Vendor</label><select name="vendor_id" defaultValue={po.vendor_id || ''}><option value="">No vendor selected</option>{vendors?.map(v=><option key={v.id} value={v.id}>{v.vendor_name}</option>)}</select></div><div className="form-grid"><div className="field"><label>Status</label><select name="status" defaultValue={po.status}><option value="draft">Draft</option><option value="issued">Issued</option><option value="partially_received">Partially Received</option><option value="received">Received</option><option value="cancelled">Cancelled</option></select></div><div className="field"><label>Order date</label><input name="order_date" type="date" defaultValue={po.order_date} /></div></div><div className="field"><label>Requested delivery</label><input name="requested_delivery_date" type="date" defaultValue={po.requested_delivery_date || ''} /></div><div className="field"><label>Vendor quote / reference</label><input name="vendor_quote_number" defaultValue={po.vendor_quote_number || ''} /></div><div className="form-grid"><div className="field"><label>Requested by</label><input name="requested_by" defaultValue={po.requested_by || ''} /></div><div className="field"><label>Approved by</label><input name="approved_by" defaultValue={po.approved_by || ''} /></div></div><div className="field"><label>Ship to</label><textarea name="ship_to_address" rows={3} defaultValue={po.ship_to_address || project?.project_address || ''} /></div><div className="form-grid"><div className="field"><label>Sales tax %</label><input name="sales_tax_rate" type="number" step="0.0001" min="0" defaultValue={Number(po.sales_tax_rate || 0)} /></div><div className="field"><label>Shipping / freight</label><input name="shipping" type="number" step="0.01" min="0" defaultValue={Number(po.shipping || 0)} /></div></div><div className="field"><label>Notes / instructions</label><textarea name="notes" rows={5} defaultValue={po.notes || ''} /></div><button className="primary-button">Save PO</button></form>
    </section>
  </AppShell>
}
