import Link from 'next/link'
import { AppShell } from '@/components/app-shell'
import { requireUser } from '@/lib/auth'
import { createCustomer } from './actions'
import { customerDisplayName, customerIndividualNames } from '@/lib/customer-display'

export default async function CustomersPage({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const { supabase } = await requireUser(); const { q = '' } = await searchParams; const query = q.trim()
  let request = supabase.from('customers').select('*').order('updated_at', { ascending: false })
  if (query) { const safe = query.replace(/[%_,]/g, ' '); request = request.or(`first_name.ilike.%${safe}%,last_name.ilike.%${safe}%,co_client_first_name.ilike.%${safe}%,co_client_last_name.ilike.%${safe}%,company_name.ilike.%${safe}%,email.ilike.%${safe}%,phone.ilike.%${safe}%,co_client_email.ilike.%${safe}%,co_client_phone.ilike.%${safe}%`) }
  const { data: customers, error } = await request; if (error) throw new Error(error.message)
  const residential=(customers||[]).filter((c:any)=>c.customer_type==='residential').length; const commercial=(customers||[]).filter((c:any)=>c.customer_type==='commercial').length

  return <AppShell title="Customers"><div className="page-heading"><div><div className="page-kicker">Relationship management</div><h2>Customers</h2><p>Maintain one clean customer record and reuse it across projects, estimates, contracts, and billing.</p></div><div className="directory-summary"><span><b>{customers?.length??0}</b> total</span><span><b>{commercial}</b> commercial</span><span><b>{residential}</b> residential</span></div></div>
    <section className="customers-page"><form className="card customer-create-card" action={createCustomer}><div className="section-heading"><div><h3 className="section-title">Add customer</h3><p className="muted-copy">Create the customer record before starting a project.</p></div></div><div className="customer-create-grid"><div className="field"><label>Customer type</label><select name="customer_type"><option value="residential">Residential</option><option value="commercial">Commercial</option></select></div><div className="field"><label>Company <small>(optional)</small></label><input name="company_name"/></div><div className="field"><label>Primary first name</label><input name="first_name"/></div><div className="field"><label>Primary last name</label><input name="last_name"/></div><div className="field"><label>Primary email</label><input name="email" type="email"/></div><div className="field"><label>Primary phone</label><input name="phone" inputMode="tel"/></div><div className="field"><label>Second client first name <small>(optional)</small></label><input name="co_client_first_name"/></div><div className="field"><label>Second client last name <small>(optional)</small></label><input name="co_client_last_name"/></div><div className="field"><label>Second client email</label><input name="co_client_email" type="email"/></div><div className="field"><label>Second client phone</label><input name="co_client_phone" inputMode="tel"/></div><div className="field span-2"><label>Billing address</label><textarea name="billing_address" rows={2}/></div><div className="field span-2"><label>Notes</label><textarea name="notes" rows={2}/></div><div className="customer-create-action"><button className="inline-primary" type="submit">Save customer</button></div></div></form>
      <div className="card directory-card"><div className="directory-toolbar"><div><h3 className="section-title">Customer directory</h3><p className="muted-copy">Search by name, company, email, or phone.</p></div><form className="search-form" action="/customers"><input name="q" defaultValue={query} placeholder="Search customers"/><button className="secondary-button" type="submit">Search</button>{query?<Link className="text-link" href="/customers">Clear</Link>:null}</form></div>{customers?.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Customer</th><th>Type</th><th>Primary Contact</th><th>Secondary Contact</th><th className="action-col">Action</th></tr></thead><tbody>{customers.map((c:any)=><tr key={c.id}><td><Link className="row-link" href={`/customers/${c.id}`}><strong>{customerDisplayName(c,'Unnamed customer')}</strong>{c.company_name&&customerIndividualNames(c).length?<small>{customerIndividualNames(c).join(' & ')}</small>:null}</Link></td><td><span className={`badge badge-${c.customer_type}`}>{c.customer_type}</span></td><td><div className="contact-cell"><span>{c.email||'—'}</span><small>{c.phone||''}</small></div></td><td><div className="contact-cell"><span>{c.co_client_email||'—'}</span><small>{c.co_client_phone||''}</small></div></td><td><Link className="text-link" href={`/customers/${c.id}`}>Open</Link></td></tr>)}</tbody></table></div>:<div className="empty">{query?'No customers match your search.':'No customers yet.'}</div>}</div></section></AppShell>
}
