import Image from 'next/image'
import { notFound } from 'next/navigation'
import { requireUser } from '@/lib/auth'
import { customerDisplayName } from '@/lib/customer-display'

function money(v:any){return Number(v||0).toLocaleString('en-US',{style:'currency',currency:'USD'})}
function basis(v:string){return ({lump_sum:'LUMP SUM / STIPULATED SUM',time_and_materials:'TIME & MATERIALS (T&M)',unit_price:'UNIT PRICE',cost_plus:'COST PLUS FEE',gmp:'GUARANTEED MAXIMUM PRICE (GMP)',not_to_exceed:'NOT-TO-EXCEED (NTE)'} as any)[v]||v}
function lines(t:any){return String(t||'').split('\n').map((x:string)=>x.trim()).filter(Boolean)}

export default async function ProposalPrint({params}:{params:Promise<{id:string}>}){const {id}=await params;const {supabase}=await requireUser();const {data:p}=await supabase.from('commercial_proposals').select('*,projects(project_number,project_name,project_address),customers(first_name,last_name,co_client_first_name,co_client_last_name,company_name,email,phone,co_client_email,co_client_phone,billing_address),commercial_proposal_csi_sections(*),commercial_proposal_items(*)').eq('id',id).maybeSingle();if(!p)notFound();const {data:company}=await supabase.from('company_settings').select('*').limit(1).maybeSingle();const project=Array.isArray(p.projects)?p.projects[0]:p.projects;const customer=Array.isArray(p.customers)?p.customers[0]:p.customers;const sections=[...(p.commercial_proposal_csi_sections||[])].sort((a:any,b:any)=>a.sort_order-b.sort_order);const items=[...(p.commercial_proposal_items||[])].sort((a:any,b:any)=>a.sort_order-b.sort_order);const base=items.filter((i:any)=>!i.is_alternate).reduce((s:number,i:any)=>s+Number(i.quantity)*Number(i.unit_price),0);const altItems=items.filter((i:any)=>i.is_alternate);const detailed=p.template_depth==='detailed';const standard=p.template_depth!=='compact';return <main className="commercial-proposal-print"><header className="proposal-print-header"><div className="proposal-print-brand"><Image src="/ntg-logo.png" alt="Nevada Tile & Granite" width={74} height={74}/><div><h1>Nevada Tile & Granite</h1><p>{company?.address}</p><p>{company?.phone} · {company?.email}</p><p>C-19 #{company?.license_c19} · C-20 #{company?.license_c20}</p></div></div><div className="proposal-print-id"><strong>COMMERCIAL PROPOSAL</strong><span>{p.proposal_number}</span></div></header><section className="proposal-print-title"><span>{basis(p.pricing_basis)}</span><h2>{p.title}</h2><p>{project?.project_name}</p></section><section className="proposal-meta-grid"><div><span>Prepared For</span><strong>{customerDisplayName(customer)}</strong><p>{p.client_contact||''}</p><p>{p.client_email||customer?.email||''}</p>{!p.client_email && customer?.co_client_email ? <p>{customer.co_client_email}</p> : null}</div><div><span>Project</span><strong>{project?.project_number} · {project?.project_name}</strong><p>{project?.project_address||''}</p></div><div><span>Proposal</span><p><b>Date</b> {p.proposal_date}</p><p><b>Valid Through</b> {p.valid_until||'—'}</p><p><b>Prepared By</b> {p.estimator||'Kevin Melendez'}</p></div></section>
 {p.executive_summary?<section className="proposal-print-section"><h3>Proposal Summary</h3><p className="preserve-lines">{p.executive_summary}</p></section>:null}
 {standard&&(p.drawings_reference||p.specifications_reference||p.addenda_reference)?<section className="proposal-print-section"><h3>Contract Documents / Bid Basis</h3><div className="proposal-doc-grid"><div><b>Drawings</b><p className="preserve-lines">{p.drawings_reference||'Not specifically identified.'}</p></div><div><b>Specifications</b><p className="preserve-lines">{p.specifications_reference||'Not specifically identified.'}</p></div><div><b>Addenda</b><p className="preserve-lines">{p.addenda_reference||'None identified.'}</p></div></div></section>:null}
 <section className="proposal-print-section"><h3>CSI / MasterFormat Scope of Work</h3>{sections.map((s:any)=><div className="proposal-csi-print" key={s.id}><h4><span>{s.csi_code}</span>{s.csi_title}</h4><p className="preserve-lines">{s.scope_text||'Scope per proposal pricing and identified contract documents.'}</p></div>)}</section>
 <section className="proposal-print-section"><h3>Base Bid / Pricing Schedule</h3><table className="proposal-price-table"><thead><tr><th>CSI</th><th>Description</th><th>Qty</th><th>Unit</th><th>Unit Price</th><th>Total</th></tr></thead><tbody>{items.filter((i:any)=>!i.is_alternate).map((i:any)=>{const s=sections.find((x:any)=>x.id===i.csi_section_id);return <tr key={i.id}><td>{s?.csi_code||'—'}</td><td>{i.description}</td><td>{Number(i.quantity).toLocaleString()}</td><td>{i.unit}</td><td>{money(i.unit_price)}</td><td>{money(Number(i.quantity)*Number(i.unit_price))}</td></tr>})}</tbody><tfoot><tr><td colSpan={5}>BASE PROPOSAL</td><td>{money(base)}</td></tr></tfoot></table></section>
 {altItems.length?<section className="proposal-print-section"><h3>Alternates</h3><table className="proposal-price-table"><thead><tr><th>Alternate</th><th>Description</th><th>Qty</th><th>Unit</th><th>Amount</th></tr></thead><tbody>{altItems.map((i:any)=><tr key={i.id}><td>{i.alternate_label||'Alternate'}</td><td>{i.description}</td><td>{Number(i.quantity).toLocaleString()}</td><td>{i.unit}</td><td>{money(Number(i.quantity)*Number(i.unit_price))}</td></tr>)}</tbody></table>{p.alternates_notes?<p className="preserve-lines">{p.alternates_notes}</p>:null}</section>:null}
 {p.pricing_basis!=='lump_sum'?<section className="proposal-print-section"><h3>{basis(p.pricing_basis)} Commercial Terms</h3><div className="proposal-rate-print">{p.labor_rate?<p><span>Standard Labor Rate</span><b>{money(p.labor_rate)}/hr</b></p>:null}{p.overtime_rate?<p><span>Overtime Labor Rate</span><b>{money(p.overtime_rate)}/hr</b></p>:null}{p.material_markup?<p><span>Material Markup</span><b>{p.material_markup}%</b></p>:null}{p.equipment_markup?<p><span>Equipment Markup</span><b>{p.equipment_markup}%</b></p>:null}{p.subcontractor_markup?<p><span>Subcontractor Markup</span><b>{p.subcontractor_markup}%</b></p>:null}{p.cost_plus_fee?<p><span>Cost Plus Fee</span><b>{p.cost_plus_fee}%</b></p>:null}{p.not_to_exceed_amount?<p><span>Not-to-Exceed Ceiling</span><b>{money(p.not_to_exceed_amount)}</b></p>:null}{p.gmp_amount?<p><span>Guaranteed Maximum Price</span><b>{money(p.gmp_amount)}</b></p>:null}</div></section>:null}
 {p.inclusions?<section className="proposal-print-section"><h3>Inclusions</h3><ul>{lines(p.inclusions).map((x,i)=><li key={i}>{x.replace(/^[-•]\s*/,'')}</li>)}</ul></section>:null}{p.exclusions?<section className="proposal-print-section"><h3>Exclusions</h3><ul>{lines(p.exclusions).map((x,i)=><li key={i}>{x.replace(/^[-•]\s*/,'')}</li>)}</ul></section>:null}{p.clarifications?<section className="proposal-print-section"><h3>Clarifications / Qualifications</h3><ul>{lines(p.clarifications).map((x,i)=><li key={i}>{x.replace(/^[-•]\s*/,'')}</li>)}</ul></section>:null}
 {standard&&p.assumptions?<section className="proposal-print-section"><h3>Assumptions</h3><p className="preserve-lines">{p.assumptions}</p></section>:null}{p.schedule_text?<section className="proposal-print-section"><h3>Schedule / Sequencing</h3><p className="preserve-lines">{p.schedule_text}</p></section>:null}{p.payment_terms?<section className="proposal-print-section"><h3>Payment / Billing Terms</h3><p className="preserve-lines">{p.payment_terms}</p></section>:null}
 {detailed&&p.insurance_bonding?<section className="proposal-print-section"><h3>Insurance / Bonding</h3><p className="preserve-lines">{p.insurance_bonding}</p></section>:null}{standard&&p.warranty_text?<section className="proposal-print-section"><h3>Warranty</h3><p className="preserve-lines">{p.warranty_text}</p></section>:null}{detailed&&p.closeout_text?<section className="proposal-print-section"><h3>Closeout Requirements</h3><p className="preserve-lines">{p.closeout_text}</p></section>:null}
 <section className="proposal-acceptance"><h3>Proposal Acceptance</h3><p>This proposal is offered subject to the scope, pricing basis, qualifications, exclusions, contract documents, and terms stated above. Final contractual obligations are subject to the executed agreement between the parties.</p><div className="proposal-signatures"><div><span>Accepted By / Company</span><i></i><span>Name / Title</span><i></i></div><div><span>Signature</span><i></i><span>Date</span><i></i></div></div></section><footer className="proposal-print-footer">Nevada Tile & Granite · {company?.website} · {p.proposal_number}</footer></main>}
