import Image from 'next/image'
import { notFound } from 'next/navigation'
import { requireUser } from '@/lib/auth'

function money(v:any){return Number(v||0).toLocaleString('en-US',{style:'currency',currency:'USD'})}
function basis(v:string){return ({lump_sum:'LUMP SUM / STIPULATED SUM',time_and_materials:'TIME & MATERIALS (T&M)',hybrid_allowance_tm:'HYBRID — ALLOWANCES + T&M',unit_price:'UNIT PRICE',cost_plus:'COST PLUS FEE',gmp:'GUARANTEED MAXIMUM PRICE (GMP)',not_to_exceed:'NOT-TO-EXCEED (NTE)'} as any)[v]||v}
function customerName(c:any){return c?.company_name||[c?.first_name,c?.last_name].filter(Boolean).join(' ')||'Client'}
function lines(t:any){return String(t||'').split('\n').map((x:string)=>x.trim()).filter(Boolean)}
function allowanceBase(i:any){return Number(i.quantity||0)*Number(i.unit_price||0)}
function allowanceMarkup(i:any){return allowanceBase(i)*Number(i.allowance_markup_pct||0)/100}
function allowanceBudget(i:any){return allowanceBase(i)+allowanceMarkup(i)}

export default async function ProposalPrint({params}:{params:Promise<{id:string}>}){
  const {id}=await params
  const {supabase}=await requireUser()
  const {data:p}=await supabase.from('commercial_proposals').select('*,projects(project_number,project_name,project_address),customers(first_name,last_name,company_name,email,phone,billing_address),commercial_proposal_csi_sections(*),commercial_proposal_items(*),commercial_proposal_labor_rates(*),commercial_proposal_areas(*,commercial_proposal_area_labor(*))').eq('id',id).maybeSingle()
  if(!p)notFound()
  const {data:scopeLaborData}=await supabase.from('commercial_proposal_scope_labor').select('*').eq('proposal_id',id)
  const {data:company}=await supabase.from('company_settings').select('*').limit(1).maybeSingle()
  const project=Array.isArray(p.projects)?p.projects[0]:p.projects
  const customer=Array.isArray(p.customers)?p.customers[0]:p.customers
  const sections=[...(p.commercial_proposal_csi_sections||[])].sort((a:any,b:any)=>a.sort_order-b.sort_order)
  const items=[...(p.commercial_proposal_items||[])].sort((a:any,b:any)=>a.sort_order-b.sort_order)
  const laborRates=[...(p.commercial_proposal_labor_rates||[])].sort((a:any,b:any)=>a.sort_order-b.sort_order)
  const areas=[...(p.commercial_proposal_areas||[])].sort((a:any,b:any)=>a.sort_order-b.sort_order)
  const areaLaborRows=areas.flatMap((a:any)=>(a.commercial_proposal_area_labor||[]).map((x:any)=>({...x,area_name:a.area_name})))
  const scopeLaborRows=[...(scopeLaborData||[])]
  const hasScopeLabor=scopeLaborRows.some((x:any)=>Number(x.estimated_st_hours||0)+Number(x.estimated_ot_hours||0)+Number(x.estimated_dt_hours||0)>0)
  const hasAreaLabor=areaLaborRows.some((x:any)=>Number(x.estimated_st_hours||0)+Number(x.estimated_ot_hours||0)+Number(x.estimated_dt_hours||0)>0)
  const displayLabor=laborRates.map((r:any)=>{const scopeRows=scopeLaborRows.filter((x:any)=>x.labor_rate_id===r.id);const areaRows=areaLaborRows.filter((x:any)=>x.labor_rate_id===r.id);const rows=hasScopeLabor?scopeRows:areaRows;const useRows=hasScopeLabor||hasAreaLabor;const st=useRows?rows.reduce((z:number,x:any)=>z+Number(x.estimated_st_hours||0),0):Number(r.estimated_st_hours||0);const ot=useRows?rows.reduce((z:number,x:any)=>z+Number(x.estimated_ot_hours||0),0):Number(r.estimated_ot_hours||0);const dt=useRows?rows.reduce((z:number,x:any)=>z+Number(x.estimated_dt_hours||0),0):Number(r.estimated_dt_hours||0);return {...r,display_st_hours:st,display_ot_hours:ot,display_dt_hours:dt}})
  const baseItems=items.filter((i:any)=>!i.is_alternate)
  const allowanceItems=baseItems.filter((i:any)=>i.category==='allowance')
  const unassignedAllowanceItems=allowanceItems.filter((i:any)=>!i.area_id)
  const regularItems=baseItems.filter((i:any)=>i.category!=='allowance')
  const regularBase=regularItems.reduce((s:number,i:any)=>s+Number(i.quantity)*Number(i.unit_price),0)
  const allowanceBaseTotal=allowanceItems.reduce((s:number,i:any)=>s+allowanceBase(i),0)
  const allowanceMarkupTotal=allowanceItems.reduce((s:number,i:any)=>s+allowanceMarkup(i),0)
  const allowanceTotal=allowanceBaseTotal+allowanceMarkupTotal
  const altItems=items.filter((i:any)=>i.is_alternate)
  const projectedLaborBilling=displayLabor.reduce((s:number,r:any)=>s+Number(r.display_st_hours||0)*Number(r.client_st_rate||0)+Number(r.display_ot_hours||0)*Number(r.client_ot_rate||0)+Number(r.display_dt_hours||0)*Number(r.client_dt_rate||0),0)
  const systemEstimate=regularBase+allowanceTotal+projectedLaborBilling
  const budgetEstimate=Number(p.estimated_project_cost||0)||systemEstimate
  const estimatedAdjustment=budgetEstimate-systemEstimate
  const totalEstimatedStHours=displayLabor.reduce((s:number,r:any)=>s+Number(r.display_st_hours||0),0)
  const totalEstimatedOtHours=displayLabor.reduce((s:number,r:any)=>s+Number(r.display_ot_hours||0),0)
  const totalEstimatedDtHours=displayLabor.reduce((s:number,r:any)=>s+Number(r.display_dt_hours||0),0)
  const totalEstimatedLaborHours=totalEstimatedStHours+totalEstimatedOtHours+totalEstimatedDtHours
  const detailed=p.template_depth==='detailed'
  const standard=p.template_depth!=='compact'
  const separateSheets=p.separate_trade_sheets!==false && sections.length>1
  const tmLike=p.pricing_basis==='time_and_materials'||p.pricing_basis==='hybrid_allowance_tm'

  return <main className="commercial-proposal-print">
    <header className="proposal-print-header"><div className="proposal-print-brand"><Image src="/ntg-logo.png" alt="Nevada Tile & Granite" width={74} height={74}/><div><h1>Nevada Tile & Granite</h1><p>{company?.address}</p><p>{company?.phone} · {company?.email}</p><p>C-19 #{company?.license_c19} · C-20 #{company?.license_c20}</p></div></div><div className="proposal-print-id"><strong>COMMERCIAL PROPOSAL</strong><span>{p.proposal_number}</span></div></header>
    <section className="proposal-print-title"><span>{basis(p.pricing_basis)}</span><h2>{p.title}</h2><p>{project?.project_name}</p></section>
    <section className="proposal-meta-grid"><div><span>Prepared For</span><strong>{customerName(customer)}</strong><p>{p.client_contact||''}</p><p>{p.client_email||customer?.email||''}</p></div><div><span>Project</span><strong>{project?.project_number} · {project?.project_name}</strong><p>{project?.project_address||''}</p></div><div><span>Proposal</span><p><b>Date</b> {p.proposal_date}</p><p><b>Valid Through</b> {p.valid_until||'—'}</p><p><b>Prepared By</b> {p.estimator||'Kevin Melendez'}</p></div></section>

    {p.executive_summary?<section className="proposal-print-section"><h3>Proposal Summary</h3><p className="preserve-lines">{p.executive_summary}</p></section>:null}
    {tmLike&&p.show_estimated_project_cost!==false&&budgetEstimate>0?<section className="proposal-print-section proposal-budget-estimate"><h3>Estimated Project Cost — Budgetary</h3><div className="proposal-budget-amount">{money(budgetEstimate)}</div><table className="proposal-price-table proposal-budget-breakdown proposal-table-budget"><tbody><tr><td>Estimated Union Labor</td><td>{totalEstimatedLaborHours.toLocaleString()} estimated hours</td><td>{money(projectedLaborBilling)}</td></tr>{allowanceTotal>0?<tr><td>Material Allowances</td><td>Including stated allowance markups</td><td>{money(allowanceTotal)}</td></tr>:null}{regularBase>0?<tr><td>Other Proposal Pricing</td><td>Non-allowance proposal items</td><td>{money(regularBase)}</td></tr>:null}{Math.abs(estimatedAdjustment)>0.009?<tr><td>Budget Adjustment / Other</td><td>Manual estimated-project-cost adjustment</td><td>{money(estimatedAdjustment)}</td></tr>:null}</tbody><tfoot><tr><td colSpan={2}>ESTIMATED PROJECT COST</td><td>{money(budgetEstimate)}</td></tr></tfoot></table><p className="preserve-lines">{p.estimated_project_cost_notes||'Estimated project cost is provided for budgeting purposes only. Final compensation will be based on actual authorized T&M labor, approved costs, applicable markups, and allowance reconciliation under the agreement.'}</p></section>:null}
    {standard&&(p.drawings_reference||p.specifications_reference||p.addenda_reference)?<section className="proposal-print-section"><h3>Contract Documents / Bid Basis</h3><div className="proposal-doc-grid"><div><b>Drawings</b><p className="preserve-lines">{p.drawings_reference||'Not specifically identified.'}</p></div><div><b>Specifications</b><p className="preserve-lines">{p.specifications_reference||'Not specifically identified.'}</p></div><div><b>Addenda</b><p className="preserve-lines">{p.addenda_reference||'None identified.'}</p></div></div></section>:null}

    {sections.map((s:any,index:number)=>{
      const sectionItems=regularItems.filter((i:any)=>i.csi_section_id===s.id&&!i.area_id)
      const subtotal=sectionItems.reduce((sum:number,i:any)=>sum+Number(i.quantity)*Number(i.unit_price),0)
      return <section key={s.id} className="proposal-print-section proposal-trade-sheet" style={separateSheets&&index>0?{breakBefore:'page'}:undefined}>
        <h3>Scope of Work</h3>
        <div className="proposal-csi-print"><h4><span>{s.csi_code}</span>{s.csi_title}</h4><p className="preserve-lines">{s.scope_text||'Scope per proposal pricing and identified contract documents.'}</p></div>
        {sectionItems.length?<><h3>{s.csi_title} — Pricing Schedule</h3><table className="proposal-price-table proposal-table-pricing"><thead><tr><th>Description</th><th>Qty</th><th>Unit</th><th>Unit Price</th><th>Total</th></tr></thead><tbody>{sectionItems.map((i:any)=><tr key={i.id}><td>{i.description}</td><td>{Number(i.quantity).toLocaleString()}</td><td>{i.unit}</td><td>{money(i.unit_price)}</td><td>{money(Number(i.quantity)*Number(i.unit_price))}</td></tr>)}</tbody><tfoot><tr><td colSpan={4}>{s.csi_code} SUBTOTAL</td><td>{money(subtotal)}</td></tr></tfoot></table></>:null}
      </section>
    })}

    {areas.length&&tmLike?<section className="proposal-print-section proposal-area-budget"><h3>Estimated T&M Budget by Area</h3><p>The following breakdown allocates the current budgetary estimate by work area. Amounts are estimates only; final billing remains based on actual authorized T&M labor, approved costs, stated markups, and allowance reconciliation.</p><table className="proposal-price-table proposal-table-area-budget"><thead><tr><th>Area / Phase</th><th>Estimated Union Hours</th><th>Estimated Union Labor</th><th>Material Allowances</th><th>Other T&M / Pricing</th><th>Estimated Area Total</th></tr></thead><tbody>{areas.map((a:any)=>{const al=a.commercial_proposal_area_labor||[];const labor=al.reduce((sum:number,x:any)=>{const r=laborRates.find((q:any)=>q.id===x.labor_rate_id);return sum+(r?Number(x.estimated_st_hours||0)*Number(r.client_st_rate||0)+Number(x.estimated_ot_hours||0)*Number(r.client_ot_rate||0)+Number(x.estimated_dt_hours||0)*Number(r.client_dt_rate||0):0)},0);const hrs=al.reduce((sum:number,x:any)=>sum+Number(x.estimated_st_hours||0)+Number(x.estimated_ot_hours||0)+Number(x.estimated_dt_hours||0),0);const ai=baseItems.filter((i:any)=>i.area_id===a.id);const allowances=ai.filter((i:any)=>i.category==='allowance').reduce((sum:number,i:any)=>sum+allowanceBudget(i),0);const other=ai.filter((i:any)=>i.category!=='allowance'&&i.category!=='labor').reduce((sum:number,i:any)=>sum+Number(i.quantity||0)*Number(i.unit_price||0),0);return <tr key={a.id}><td><strong>{a.area_name}</strong>{a.notes?<><br/><small>{a.notes}</small></>:null}</td><td>{hrs.toLocaleString()} hrs</td><td>{money(labor)}</td><td>{money(allowances)}</td><td>{money(other)}</td><td><strong>{money(labor+allowances+other)}</strong></td></tr>})}</tbody><tfoot><tr><td>AREA BREAKDOWN TOTAL</td><td>{areas.reduce((sum:number,a:any)=>sum+(a.commercial_proposal_area_labor||[]).reduce((z:number,x:any)=>z+Number(x.estimated_st_hours||0)+Number(x.estimated_ot_hours||0)+Number(x.estimated_dt_hours||0),0),0).toLocaleString()} hrs</td><td>{money(areas.reduce((sum:number,a:any)=>sum+(a.commercial_proposal_area_labor||[]).reduce((z:number,x:any)=>{const r=laborRates.find((q:any)=>q.id===x.labor_rate_id);return z+(r?Number(x.estimated_st_hours||0)*Number(r.client_st_rate||0)+Number(x.estimated_ot_hours||0)*Number(r.client_ot_rate||0)+Number(x.estimated_dt_hours||0)*Number(r.client_dt_rate||0):0)},0),0))}</td><td>{money(baseItems.filter((i:any)=>i.area_id&&i.category==='allowance').reduce((sum:number,i:any)=>sum+allowanceBudget(i),0))}</td><td>{money(baseItems.filter((i:any)=>i.area_id&&i.category!=='allowance'&&i.category!=='labor').reduce((sum:number,i:any)=>sum+Number(i.quantity||0)*Number(i.unit_price||0),0))}</td><td></td></tr></tfoot></table></section>:null}

    {(hasScopeLabor||hasAreaLabor)&&((hasScopeLabor?scopeLaborRows:areaLaborRows).some((x:any)=>x.csi_section_id&&(Number(x.estimated_st_hours||0)+Number(x.estimated_ot_hours||0)+Number(x.estimated_dt_hours||0)>0)))?<section className="proposal-print-section"><h3>Estimated Union Labor by Scope</h3><p>Estimated union labor is allocated to the applicable CSI scope for proposal breakdown purposes. These allocations are estimates and remain subject to the stated proposal pricing basis.</p><table className="proposal-price-table proposal-table-labor"><thead><tr><th>CSI Scope</th><th>Classification</th><th>ST Hours</th><th>OT Hours</th><th>DT Hours</th><th>Total Hours</th><th>Estimated Amount</th></tr></thead><tbody>{sections.flatMap((sec:any)=>laborRates.map((r:any)=>{const sourceRows=hasScopeLabor?scopeLaborRows:areaLaborRows;const rows=sourceRows.filter((x:any)=>x.csi_section_id===sec.id&&x.labor_rate_id===r.id);const st=rows.reduce((z:number,x:any)=>z+Number(x.estimated_st_hours||0),0);const ot=rows.reduce((z:number,x:any)=>z+Number(x.estimated_ot_hours||0),0);const dt=rows.reduce((z:number,x:any)=>z+Number(x.estimated_dt_hours||0),0);const hrs=st+ot+dt;if(!hrs)return null;const amount=st*Number(r.client_st_rate||0)+ot*Number(r.client_ot_rate||0)+dt*Number(r.client_dt_rate||0);return <tr key={`${sec.id}-${r.id}`}><td><strong>{sec.csi_code}</strong><br/><span>{sec.csi_title}</span></td><td>{r.classification}</td><td>{st.toLocaleString()}</td><td>{ot.toLocaleString()}</td><td>{dt.toLocaleString()}</td><td>{hrs.toLocaleString()}</td><td>{money(amount)}</td></tr>})).filter(Boolean)}</tbody></table></section>:null}
    {allowanceItems.length?<section className="proposal-print-section"><h3>Material Allowance Schedule</h3><p>This schedule provides the detailed basis for all material allowances included in the proposal, including items assigned to an Area / Phase. Area-assigned allowances may also be summarized in the Estimated T&M Budget by Area for management review; they are not added a second time to the proposal total.</p><table className="proposal-price-table proposal-allowance-table proposal-table-allowances"><thead><tr><th>Allowance</th><th>Area / Phase</th><th>Qty / Unit</th><th>Allowance Unit Rate</th><th>Base Allowance</th><th>Markup</th><th>Budgeted Total</th></tr></thead><tbody>{allowanceItems.map((i:any)=>{const area=areas.find((a:any)=>a.id===i.area_id);return <tr key={i.id}><td>{i.description}</td><td>{area?.area_name||'General / Unassigned'}</td><td>{Number(i.quantity).toLocaleString()} {i.unit}</td><td>{money(i.unit_price)}/{i.unit||'unit'}</td><td>{money(allowanceBase(i))}</td><td>{Number(i.allowance_markup_pct||0)>0?`${Number(i.allowance_markup_pct).toLocaleString()}% (${money(allowanceMarkup(i))})`:'—'}</td><td>{money(allowanceBudget(i))}</td></tr>})}</tbody><tfoot><tr><td colSpan={4}>TOTAL MATERIAL ALLOWANCES</td><td>{money(allowanceBaseTotal)}</td><td>{money(allowanceMarkupTotal)}</td><td>{money(allowanceTotal)}</td></tr></tfoot></table><p>Allowance quantities and unit rates establish the current budget basis. Final allowance billing remains subject to actual authorized quantities/costs, stated markups, and the terms of the executed agreement.</p></section>:null}

    {laborRates.length?<section className="proposal-print-section"><h3>Estimated Union Labor</h3><p>{tmLike?'Estimated labor hours are provided to support the budgetary project-cost breakdown. Actual billing will be based on authorized hours worked and the applicable NTG billing rates.':`Estimated union labor hours are provided as a supporting scope and staffing breakdown. The proposal remains ${basis(p.pricing_basis)} and these estimated hours do not change the stated pricing basis.`}</p><table className={`proposal-price-table proposal-table-labor ${p.show_client_labor_rates===false?'rates-hidden':'rates-visible'}`}><thead><tr><th>Classification</th><th>ST Hours</th><th>OT Hours</th><th>DT Hours</th><th>Total Hours</th>{p.show_client_labor_rates!==false?<><th>Billing Rates</th><th>Estimated Amount</th></>:null}</tr></thead><tbody>{displayLabor.map((r:any)=>{const st=Number(r.display_st_hours||0);const ot=Number(r.display_ot_hours||0);const dt=Number(r.display_dt_hours||0);const hrs=st+ot+dt;const amount=st*Number(r.client_st_rate||0)+ot*Number(r.client_ot_rate||0)+dt*Number(r.client_dt_rate||0);return <tr key={r.id}><td>{r.classification}</td><td>{st.toLocaleString()}</td><td>{ot.toLocaleString()}</td><td>{dt.toLocaleString()}</td><td>{hrs.toLocaleString()}</td>{p.show_client_labor_rates!==false?<><td><span>ST {money(r.client_st_rate)}/hr</span><br/><span>OT {money(r.client_ot_rate)}/hr</span><br/><span>DT {money(r.client_dt_rate)}/hr</span></td><td>{money(amount)}</td></>:null}</tr>})}</tbody><tfoot><tr><td>TOTAL ESTIMATED UNION LABOR</td><td>{totalEstimatedStHours.toLocaleString()}</td><td>{totalEstimatedOtHours.toLocaleString()}</td><td>{totalEstimatedDtHours.toLocaleString()}</td><td>{totalEstimatedLaborHours.toLocaleString()}</td>{p.show_client_labor_rates!==false?<><td></td><td>{money(projectedLaborBilling)}</td></>:null}</tr></tfoot></table>{p.show_client_labor_rates===false?<p><b>Estimated labor component:</b> {money(projectedLaborBilling)}. Individual NTG billing rates are omitted from this proposal.</p>:<p>The rates shown are Nevada Tile & Granite customer billing rates, not employee wage or fringe-benefit rates.</p>}{p.tm_labor_terms?<p className="preserve-lines">{p.tm_labor_terms}</p>:null}</section>:null}

    {regularItems.some((i:any)=>!i.csi_section_id&&!i.area_id)?<section className="proposal-print-section"><h3>Unassigned / General Pricing</h3><table className="proposal-price-table proposal-table-pricing"><thead><tr><th>Description</th><th>Qty</th><th>Unit</th><th>Unit Price</th><th>Total</th></tr></thead><tbody>{regularItems.filter((i:any)=>!i.csi_section_id&&!i.area_id).map((i:any)=><tr key={i.id}><td>{i.description}</td><td>{Number(i.quantity).toLocaleString()}</td><td>{i.unit}</td><td>{money(i.unit_price)}</td><td>{money(Number(i.quantity)*Number(i.unit_price))}</td></tr>)}</tbody></table></section>:null}

    {p.pricing_basis==='lump_sum'?<section className="proposal-print-section proposal-budget-estimate"><h3>Proposal Price Summary</h3><table className="proposal-price-table proposal-table-summary"><thead><tr><th>Scope / Component</th><th>Other Pricing</th><th>Union Labor</th><th>Total</th></tr></thead><tbody>{sections.map((sec:any)=>{const pricing=baseItems.filter((i:any)=>i.csi_section_id===sec.id).reduce((sum:number,i:any)=>sum+(i.category==='allowance'?allowanceBudget(i):Number(i.quantity||0)*Number(i.unit_price||0)),0);const sourceRows=hasScopeLabor?scopeLaborRows:(hasAreaLabor?areaLaborRows:[]);const labor=sourceRows.length?sourceRows.filter((x:any)=>x.csi_section_id===sec.id).reduce((sum:number,x:any)=>{const r=laborRates.find((q:any)=>q.id===x.labor_rate_id);return sum+(r?Number(x.estimated_st_hours||0)*Number(r.client_st_rate||0)+Number(x.estimated_ot_hours||0)*Number(r.client_ot_rate||0)+Number(x.estimated_dt_hours||0)*Number(r.client_dt_rate||0):0)},0):0;return (pricing||labor)?<tr key={sec.id}><td><strong>{sec.csi_code}</strong> · {sec.csi_title}</td><td>{money(pricing)}</td><td>{money(labor)}</td><td><strong>{money(pricing+labor)}</strong></td></tr>:null})}{baseItems.filter((i:any)=>!i.csi_section_id).length?<tr><td>General / Unassigned Pricing</td><td>{money(baseItems.filter((i:any)=>!i.csi_section_id).reduce((sum:number,i:any)=>sum+(i.category==='allowance'?allowanceBudget(i):Number(i.quantity||0)*Number(i.unit_price||0)),0))}</td><td>{money(0)}</td><td>{money(baseItems.filter((i:any)=>!i.csi_section_id).reduce((sum:number,i:any)=>sum+(i.category==='allowance'?allowanceBudget(i):Number(i.quantity||0)*Number(i.unit_price||0)),0))}</td></tr>:null}{(!hasScopeLabor&&!hasAreaLabor&&projectedLaborBilling>0)?<tr><td>Estimated Union Labor</td><td>{money(0)}</td><td>{money(projectedLaborBilling)}</td><td><strong>{money(projectedLaborBilling)}</strong></td></tr>:null}{(hasScopeLabor||hasAreaLabor)&&(()=>{const sourceRows=hasScopeLabor?scopeLaborRows:areaLaborRows;const unallocated=sourceRows.filter((x:any)=>!x.csi_section_id).reduce((sum:number,x:any)=>{const r=laborRates.find((q:any)=>q.id===x.labor_rate_id);return sum+(r?Number(x.estimated_st_hours||0)*Number(r.client_st_rate||0)+Number(x.estimated_ot_hours||0)*Number(r.client_ot_rate||0)+Number(x.estimated_dt_hours||0)*Number(r.client_dt_rate||0):0)},0);return unallocated?<tr><td>General / Unallocated Union Labor</td><td>{money(0)}</td><td>{money(unallocated)}</td><td><strong>{money(unallocated)}</strong></td></tr>:null})()}</tbody><tfoot><tr><td>TOTAL PROPOSAL</td><td>{money(regularBase+allowanceTotal)}</td><td>{money(projectedLaborBilling)}</td><td>{money(regularBase+allowanceTotal+projectedLaborBilling)}</td></tr></tfoot></table><p>This total combines the proposal pricing schedule, material allowances including stated markups, and estimated union labor at the NTG customer billing rates shown in this proposal.</p></section>:null}
    {altItems.length?<section className="proposal-print-section"><h3>Alternates</h3><table className="proposal-price-table proposal-table-alternates"><thead><tr><th>Alternate</th><th>Description</th><th>Qty</th><th>Unit</th><th>Amount</th></tr></thead><tbody>{altItems.map((i:any)=><tr key={i.id}><td>{i.alternate_label||'Alternate'}</td><td>{i.description}</td><td>{Number(i.quantity).toLocaleString()}</td><td>{i.unit}</td><td>{money(Number(i.quantity)*Number(i.unit_price))}</td></tr>)}</tbody></table>{p.alternates_notes?<p className="preserve-lines">{p.alternates_notes}</p>:null}</section>:null}
    {p.pricing_basis!=='lump_sum'?<section className="proposal-print-section"><h3>{basis(p.pricing_basis)} Commercial Terms</h3><div className="proposal-rate-print">{p.material_markup?<p><span>Material Markup</span><b>{p.material_markup}%</b></p>:null}{p.equipment_markup?<p><span>Equipment Markup</span><b>{p.equipment_markup}%</b></p>:null}{p.subcontractor_markup?<p><span>Subcontractor Markup</span><b>{p.subcontractor_markup}%</b></p>:null}{p.cost_plus_fee?<p><span>Cost Plus Fee</span><b>{p.cost_plus_fee}%</b></p>:null}{p.not_to_exceed_amount?<p><span>Not-to-Exceed Ceiling</span><b>{money(p.not_to_exceed_amount)}</b></p>:null}{p.gmp_amount?<p><span>Guaranteed Maximum Price</span><b>{money(p.gmp_amount)}</b></p>:null}</div></section>:null}
    {p.inclusions?<section className="proposal-print-section"><h3>Inclusions</h3><ul>{lines(p.inclusions).map((x,i)=><li key={i}>{x.replace(/^[-•]\s*/,'')}</li>)}</ul></section>:null}
    {p.exclusions?<section className="proposal-print-section"><h3>Exclusions</h3><ul>{lines(p.exclusions).map((x,i)=><li key={i}>{x.replace(/^[-•]\s*/,'')}</li>)}</ul></section>:null}
    {p.clarifications?<section className="proposal-print-section"><h3>Clarifications / Qualifications</h3><ul>{lines(p.clarifications).map((x,i)=><li key={i}>{x.replace(/^[-•]\s*/,'')}</li>)}</ul></section>:null}
    {standard&&p.assumptions?<section className="proposal-print-section"><h3>Assumptions</h3><p className="preserve-lines">{p.assumptions}</p></section>:null}
    {p.schedule_text?<section className="proposal-print-section"><h3>Schedule / Sequencing</h3><p className="preserve-lines">{p.schedule_text}</p></section>:null}
    {p.payment_terms?<section className="proposal-print-section"><h3>Payment / Billing Terms</h3><p className="preserve-lines">{p.payment_terms}</p></section>:null}
    {detailed&&p.insurance_bonding?<section className="proposal-print-section"><h3>Insurance / Bonding</h3><p className="preserve-lines">{p.insurance_bonding}</p></section>:null}
    {standard&&p.warranty_text?<section className="proposal-print-section"><h3>Warranty</h3><p className="preserve-lines">{p.warranty_text}</p></section>:null}
    {detailed&&p.closeout_text?<section className="proposal-print-section"><h3>Closeout Requirements</h3><p className="preserve-lines">{p.closeout_text}</p></section>:null}
    <section className="proposal-acceptance"><h3>Proposal Acceptance</h3><p>This proposal is offered subject to the scope, pricing basis, qualifications, exclusions, contract documents, allowances, billing rates, and terms stated above. Final contractual obligations are subject to the executed agreement between the parties.</p><div className="proposal-signatures"><div><span>Accepted By / Company</span><i></i><span>Name / Title</span><i></i></div><div><span>Signature</span><i></i><span>Date</span><i></i></div></div></section>
    <footer className="proposal-print-footer">Nevada Tile & Granite · {company?.website} · {p.proposal_number}</footer>
  </main>
}
