-- NTG Project Hub v0.1 initial schema
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  role text not null default 'owner' check (role in ('owner','administrator','estimator','project_manager','accounting')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  customer_type text not null default 'residential' check (customer_type in ('residential','commercial')),
  first_name text,
  last_name text,
  company_name text,
  email text,
  phone text,
  billing_address text,
  notes text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.project_sequences (
  year integer primary key,
  current_value integer not null default 0
);

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  project_number text unique,
  customer_id uuid references public.customers(id) on delete set null,
  project_name text not null,
  project_address text,
  project_type text not null default 'residential' check (project_type in ('residential','commercial')),
  status text not null default 'lead' check (status in ('lead','estimating','awarded','active','on_hold','complete','closed')),
  contract_amount numeric(12,2) not null default 0,
  notes text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.company_settings (
  id uuid primary key default gen_random_uuid(),
  company_name text not null,
  phone text,
  email text,
  website text,
  address text,
  license_c19 text,
  license_c20 text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  project_id uuid references public.projects(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.assign_project_number()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  y integer := extract(year from now())::integer;
  next_value integer;
begin
  if new.project_number is null or btrim(new.project_number) = '' then
    insert into public.project_sequences(year, current_value)
    values (y, 1)
    on conflict (year) do update set current_value = public.project_sequences.current_value + 1
    returning current_value into next_value;
    new.project_number := 'PRJ-' || right(y::text, 2) || '-' || lpad(next_value::text, 4, '0');
  end if;
  if new.created_by is null then new.created_by := auth.uid(); end if;
  return new;
end;
$$;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id, email, full_name, role)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'full_name',''), 'owner')
  on conflict (id) do nothing;
  return new;
end;
$$;

create or replace function public.set_created_by()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.created_by is null then new.created_by := auth.uid(); end if;
  return new;
end;
$$;

insert into public.profiles(id, email, full_name, role)
select id, coalesce(email, ''), coalesce(raw_user_meta_data->>'full_name',''), 'owner'
from auth.users
on conflict (id) do nothing;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
drop trigger if exists projects_assign_number on public.projects;
create trigger projects_assign_number before insert on public.projects for each row execute function public.assign_project_number();
drop trigger if exists customers_set_created_by on public.customers;
create trigger customers_set_created_by before insert on public.customers for each row execute function public.set_created_by();
drop trigger if exists profiles_updated_at on public.profiles;
create trigger profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
drop trigger if exists customers_updated_at on public.customers;
create trigger customers_updated_at before update on public.customers for each row execute function public.set_updated_at();
drop trigger if exists projects_updated_at on public.projects;
create trigger projects_updated_at before update on public.projects for each row execute function public.set_updated_at();
drop trigger if exists company_settings_updated_at on public.company_settings;
create trigger company_settings_updated_at before update on public.company_settings for each row execute function public.set_updated_at();

insert into public.company_settings(company_name, phone, email, website, address, license_c19, license_c20)
select 'Nevada Tile & Granite', '(725) 275-7145', 'kevin@nevadatileandgranite.com', 'nevadatileandgranite.com', '1404 E Webb Ave, North Las Vegas, NV 89030', '0093403', '0093447'
where not exists (select 1 from public.company_settings);

alter table public.profiles enable row level security;
alter table public.customers enable row level security;
alter table public.projects enable row level security;
alter table public.company_settings enable row level security;
alter table public.activity_logs enable row level security;

create policy "authenticated profiles read" on public.profiles for select to authenticated using (true);
create policy "users update own profile" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
create policy "authenticated customers all" on public.customers for all to authenticated using (true) with check (true);
create policy "authenticated projects all" on public.projects for all to authenticated using (true) with check (true);
create policy "authenticated company settings read" on public.company_settings for select to authenticated using (true);
create policy "owners company settings update" on public.company_settings for update to authenticated using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('owner','administrator'))) with check (true);
create policy "authenticated activity read" on public.activity_logs for select to authenticated using (true);
create policy "authenticated activity insert" on public.activity_logs for insert to authenticated with check (user_id is null or user_id = auth.uid());

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.customers, public.projects to authenticated;
grant select on public.company_settings, public.profiles, public.activity_logs to authenticated;
grant update on public.company_settings, public.profiles to authenticated;
grant insert on public.activity_logs to authenticated;
grant usage, select on all sequences in schema public to authenticated;
